[package]
name = "procon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "3.0.0"
path-clean = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_norway = "0.9.42"
